### ISSUE TITLE
in 1st step composer install get errors

### ISSUE THREAD

**Issue by atscoacaddemy** [zizohassan/video-website#1]
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
In Connection.php line 664:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'youtube.categories' doesn't exist (SQL:
select * from `categories`)
In Connection.php line 326:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'youtube.categories' doesn't exist
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
<hr>
<a href="https://ibb.co/Kj4svyT"><img src="https://i.ibb.co/27VM4KG/yyy.png" alt="yyy" border="0" /></a>

**Comment by zizohassan** [comment]
go to this path

```
app/Providers/AppServiceProvider.php
```

then comment this lines 

```
   view()->share('categories' , Category::get());
        view()->share('skills' , Skill::get());
        view()->share('pages' , Page::get());
```

then 

```
composer install 
```

then after migrate remove comment 

this will fix the issue

Best

**Comment by atscoacaddemy** [comment]
goode done and completed .

http://127.0.0.1:8000/admin not working give me 404 Not Found

**Comment by zizohassan** [comment]
http://127.0.0.1:8000/admin/home 

will work with you 
you can check the routes files 

Best
